version: '3'
services:

    php:
        build:
            context: ./docker/php
            dockerfile: ./Dockerfile
        volumes:
            - .:/var/www/html:cached
        networks:
            - app-network
        tty: true
        environment:
            XDEBUG_CONFIG: remote_host=10.254.254.254
            PHP_IDE_CONFIG: serverName=localhost
    #PHP Service
    php-fpm:
        build:
            context: ./docker/php-fpm
            dockerfile: ./Dockerfile
            args:
                XDEBUG_ENABLE: ${XDEBUG_ENABLE}
        expose:
            - 9000
        volumes:
            - .:/var/www/html:cached
        networks:
            - app-network
        tty: true
        environment:
            XDEBUG_CONFIG: remote_host=10.254.254.254
            PHP_IDE_CONFIG: serverName=localhost

    #Nginx Service
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html:cached
        depends_on:
            - php-fpm
        networks:
            - app-network

    #MySQL Service
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        expose:
            - ${DB_PORT}
        ports:
            - ${DB_PORT}:${DB_PORT}
        networks:
            - app-network
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}


#Docker Networks
networks:
    app-network:
        driver: bridge
